{ pkgs, ... }:
{
  # Used to find the project root
  projectRootFile = "flake.nix";

  programs.nixfmt.enable = true;

  # Files to exclude from formatting.
  settings.global.excludes = [
    # Generated by tree-sitter
    "src/**"

    # Exclude non-Nix code for now.
    ".editorconfig"
    ".gitattributes"
    "CMakeLists.txt"
    "Cargo.toml"
    "Makefile"
    "Package.swift"
    "binding.gyp"
    "bindings/**"
    "grammar.js"
    "package.json"
    "pyproject.toml"
    "queries/**"
    "setup.py"
    "test/**"
    "tree-sitter.json"

    # Other misc files (these probably don't belong in the repo)
    "example-file"
    "func.lisp"
    "test.lisp"
  ];
}
